name: Update Profile README

on:
  schedule:
    - cron: "0 */12 * * *" # Executa duas vezes por dia
  workflow_dispatch: # Permite execução manual
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate GitHub stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Update README.md
        run: |
          # Atualiza estatísticas do GitHub
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/users/${{ github.repository_owner }} > stats.json

          # Atualiza o README com os dados mais recentes
          cat > README.md << EOF
          <div align="center">
            <h1>👋 Olá, eu sou Ednei Trabach</h1>
            
            ![Visualizações](https://komarev.com/ghpvc/?username=edneitrabach&label=Visualizações&color=0e75b6&style=flat)
            
            [![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=edneitrabach&theme=dracula)](https://git.io/streak-stats)
            
            ![Linguagens Mais Usadas](https://github-readme-stats.vercel.app/api/top-langs/?username=edneitrabach&layout=compact&theme=dracula)
            
            ![Contribuições](./dist/github-contribution-grid-snake.svg)
          </div>
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md dist/
          git commit -m "docs: atualiza README com estatísticas mais recentes"
          git push
